scan_filter_chain:
  - name: shadows
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 10
      max_angle: 170
      neighbors: 20
      window: 1

  - name: dark_shadows
    type: laser_filters/LaserScanIntensityFilter
      params:
        lower_threshold: 100
        upper_threshold: 10000
        disp_histogram: 0
  - name: box
    type: laser_filters/LaserScanBoxFilter
       params:
          box_frame: scan_link
          min_x: -2.0
          max_x: 1.0
          min_y: -1.0
          max_y: 1.0
          min_z: -1.0
          max_z: 1.0